apiVersion: v1
kind: Service
metadata:
  name: monolit-service
  namespace: udagram
  labels:
    app: monolit-backend
spec:
  selector:
    app: monolit-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolit-deployment
  namespace: udagram
  labels:
    app: monolit-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolit-backend
  template:
    metadata:
      labels:
        app: monolit-backend
    spec:
      containers:
      - name: monolit-backend-container
        image: ybsnek/udagram-monolit
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_HOST
          value: database-1.ctpfwg4b3n2v.eu-north-1.rds.amazonaws.com
        - name: POSTGRES_DB
          value: udagram
        - name: JWT_SECRET
          value: hello
        - name: URL
          value: http://a9efea34b32ce409195e1878b6e8aceb-0b290277e49844bf.elb.eu-north-1.amazonaws.com
        - name: AWS_BUCKET
          value: udagram-ybsnek-dev
        - name: AWS_REGION
          value: eu-north-1
        - name: AWS_PROFILE
          value: default
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY